security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        fos_userbundle:
            id: fos_user.user_provider.username_email

        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                provider: fos_userbundle
                check_path:               /api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            provider: fos_userbundle

        main:
            pattern: ^/
            form_login:
                csrf_token_generator: security.csrf.token_manager
                provider:     fos_userbundle
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
            remember_me: 
                secret: 
                    '%kernel.secret%'
                
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true
            
      
        
        
                
        api:
            pattern:   ^/api/review/new
            stateless: true
            provider: fos_userbundle
            # ATTENTION A NE PAS GARDER LA LIGNE SUIVANTE
            #security: false
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        
    access_control:
        - { path: ^/api/review/new, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/apartment, role: ROLE_ADMIN }
        - { path: ^/admin/review, role: ROLE_ADMIN  }
        - { path: ^/admin/user, role: ROLE_ADMIN  }
        